// Code generated by lister-gen. DO NOT EDIT.

package v1

// ServiceMeshControlPlaneListerExpansion allows custom methods to be added to
// ServiceMeshControlPlaneLister.
type ServiceMeshControlPlaneListerExpansion interface{}

// ServiceMeshControlPlaneNamespaceListerExpansion allows custom methods to be added to
// ServiceMeshControlPlaneNamespaceLister.
type ServiceMeshControlPlaneNamespaceListerExpansion interface{}

// ServiceMeshMemberRollListerExpansion allows custom methods to be added to
// ServiceMeshMemberRollLister.
type ServiceMeshMemberRollListerExpansion interface{}

// ServiceMeshMemberRollNamespaceListerExpansion allows custom methods to be added to
// ServiceMeshMemberRollNamespaceLister.
type ServiceMeshMemberRollNamespaceListerExpansion interface{}
