// Code generated by injection-gen. DO NOT EDIT.

package servicemeshmemberroll

import (
	"context"

	v1 "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/informers/externalversions/maistra/v1"
	factory "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/injection/maistra/informers/factory"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
	logging "knative.dev/pkg/logging"
)

func init() {
	injection.Default.RegisterInformer(withInformer)
}

// Key is used for associating the Informer inside the context.Context.
type Key struct{}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := factory.Get(ctx)
	inf := f.Maistra().V1().ServiceMeshMemberRolls()
	return context.WithValue(ctx, Key{}, inf), inf.Informer()
}

// Get extracts the typed informer from the context.
func Get(ctx context.Context) v1.ServiceMeshMemberRollInformer {
	untyped := ctx.Value(Key{})
	if untyped == nil {
		logging.FromContext(ctx).Panic(
			"Unable to fetch github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/informers/externalversions/maistra/v1.ServiceMeshMemberRollInformer from context.")
	}
	return untyped.(v1.ServiceMeshMemberRollInformer)
}
