// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/maistra/istio-operator/pkg/apis/maistra/v1"
	"github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type MaistraV1Interface interface {
	RESTClient() rest.Interface
	ServiceMeshControlPlanesGetter
	ServiceMeshMemberRollsGetter
}

// MaistraV1Client is used to interact with features provided by the maistra.io group.
type MaistraV1Client struct {
	restClient rest.Interface
}

func (c *MaistraV1Client) ServiceMeshControlPlanes(namespace string) ServiceMeshControlPlaneInterface {
	return newServiceMeshControlPlanes(c, namespace)
}

func (c *MaistraV1Client) ServiceMeshMemberRolls(namespace string) ServiceMeshMemberRollInterface {
	return newServiceMeshMemberRolls(c, namespace)
}

// NewForConfig creates a new MaistraV1Client for the given config.
func NewForConfig(c *rest.Config) (*MaistraV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &MaistraV1Client{client}, nil
}

// NewForConfigOrDie creates a new MaistraV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MaistraV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MaistraV1Client for the given RESTClient.
func New(c rest.Interface) *MaistraV1Client {
	return &MaistraV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MaistraV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
