// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/Maistra/istio-operator/pkg/apis/maistra/v1"
	scheme "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceMeshControlPlanesGetter has a method to return a ServiceMeshControlPlaneInterface.
// A group's client should implement this interface.
type ServiceMeshControlPlanesGetter interface {
	ServiceMeshControlPlanes(namespace string) ServiceMeshControlPlaneInterface
}

// ServiceMeshControlPlaneInterface has methods to work with ServiceMeshControlPlane resources.
type ServiceMeshControlPlaneInterface interface {
	Create(*v1.ServiceMeshControlPlane) (*v1.ServiceMeshControlPlane, error)
	Update(*v1.ServiceMeshControlPlane) (*v1.ServiceMeshControlPlane, error)
	UpdateStatus(*v1.ServiceMeshControlPlane) (*v1.ServiceMeshControlPlane, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ServiceMeshControlPlane, error)
	List(opts metav1.ListOptions) (*v1.ServiceMeshControlPlaneList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ServiceMeshControlPlane, err error)
	ServiceMeshControlPlaneExpansion
}

// serviceMeshControlPlanes implements ServiceMeshControlPlaneInterface
type serviceMeshControlPlanes struct {
	client rest.Interface
	ns     string
}

// newServiceMeshControlPlanes returns a ServiceMeshControlPlanes
func newServiceMeshControlPlanes(c *MaistraV1Client, namespace string) *serviceMeshControlPlanes {
	return &serviceMeshControlPlanes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceMeshControlPlane, and returns the corresponding serviceMeshControlPlane object, and an error if there is any.
func (c *serviceMeshControlPlanes) Get(name string, options metav1.GetOptions) (result *v1.ServiceMeshControlPlane, err error) {
	result = &v1.ServiceMeshControlPlane{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceMeshControlPlanes that match those selectors.
func (c *serviceMeshControlPlanes) List(opts metav1.ListOptions) (result *v1.ServiceMeshControlPlaneList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ServiceMeshControlPlaneList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceMeshControlPlanes.
func (c *serviceMeshControlPlanes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a serviceMeshControlPlane and creates it.  Returns the server's representation of the serviceMeshControlPlane, and an error, if there is any.
func (c *serviceMeshControlPlanes) Create(serviceMeshControlPlane *v1.ServiceMeshControlPlane) (result *v1.ServiceMeshControlPlane, err error) {
	result = &v1.ServiceMeshControlPlane{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		Body(serviceMeshControlPlane).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serviceMeshControlPlane and updates it. Returns the server's representation of the serviceMeshControlPlane, and an error, if there is any.
func (c *serviceMeshControlPlanes) Update(serviceMeshControlPlane *v1.ServiceMeshControlPlane) (result *v1.ServiceMeshControlPlane, err error) {
	result = &v1.ServiceMeshControlPlane{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		Name(serviceMeshControlPlane.Name).
		Body(serviceMeshControlPlane).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *serviceMeshControlPlanes) UpdateStatus(serviceMeshControlPlane *v1.ServiceMeshControlPlane) (result *v1.ServiceMeshControlPlane, err error) {
	result = &v1.ServiceMeshControlPlane{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		Name(serviceMeshControlPlane.Name).
		SubResource("status").
		Body(serviceMeshControlPlane).
		Do().
		Into(result)
	return
}

// Delete takes name of the serviceMeshControlPlane and deletes it. Returns an error if one occurs.
func (c *serviceMeshControlPlanes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceMeshControlPlanes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serviceMeshControlPlane.
func (c *serviceMeshControlPlanes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ServiceMeshControlPlane, err error) {
	result = &v1.ServiceMeshControlPlane{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicemeshcontrolplanes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
