// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ServiceMeshControlPlanes returns a ServiceMeshControlPlaneInformer.
	ServiceMeshControlPlanes() ServiceMeshControlPlaneInformer
	// ServiceMeshMemberRolls returns a ServiceMeshMemberRollInformer.
	ServiceMeshMemberRolls() ServiceMeshMemberRollInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ServiceMeshControlPlanes returns a ServiceMeshControlPlaneInformer.
func (v *version) ServiceMeshControlPlanes() ServiceMeshControlPlaneInformer {
	return &serviceMeshControlPlaneInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ServiceMeshMemberRolls returns a ServiceMeshMemberRollInformer.
func (v *version) ServiceMeshMemberRolls() ServiceMeshMemberRollInformer {
	return &serviceMeshMemberRollInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
