// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	maistrav1 "github.com/maistra/istio-operator/pkg/apis/maistra/v1"
	versioned "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/clientset/versioned"
	internalinterfaces "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/listers/maistra/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceMeshControlPlaneInformer provides access to a shared informer and lister for
// ServiceMeshControlPlanes.
type ServiceMeshControlPlaneInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ServiceMeshControlPlaneLister
}

type serviceMeshControlPlaneInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewServiceMeshControlPlaneInformer constructs a new informer for ServiceMeshControlPlane type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServiceMeshControlPlaneInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredServiceMeshControlPlaneInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredServiceMeshControlPlaneInformer constructs a new informer for ServiceMeshControlPlane type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredServiceMeshControlPlaneInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MaistraV1().ServiceMeshControlPlanes(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MaistraV1().ServiceMeshControlPlanes(namespace).Watch(options)
			},
		},
		&maistrav1.ServiceMeshControlPlane{},
		resyncPeriod,
		indexers,
	)
}

func (f *serviceMeshControlPlaneInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredServiceMeshControlPlaneInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *serviceMeshControlPlaneInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&maistrav1.ServiceMeshControlPlane{}, f.defaultInformer)
}

func (f *serviceMeshControlPlaneInformer) Lister() v1.ServiceMeshControlPlaneLister {
	return v1.NewServiceMeshControlPlaneLister(f.Informer().GetIndexer())
}
