// Code generated by injection-gen. DO NOT EDIT.

package fake

import (
	"context"

	fake "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/maistra/injection/informers/factory/fake"
	servicemeshmemberroll "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/maistra/injection/informers/maistra/v1/servicemeshmemberroll"
	controller "knative.dev/pkg/controller"
	injection "knative.dev/pkg/injection"
)

var Get = servicemeshmemberroll.Get

func init() {
	injection.Fake.RegisterInformer(withInformer)
}

func withInformer(ctx context.Context) (context.Context, controller.Informer) {
	f := fake.Get(ctx)
	inf := f.Maistra().V1().ServiceMeshMemberRolls()
	return context.WithValue(ctx, servicemeshmemberroll.Key{}, inf), inf.Informer()
}
