// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/clientset/versioned/typed/maistra/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMaistraV1 struct {
	*testing.Fake
}

func (c *FakeMaistraV1) ServiceMeshControlPlanes(namespace string) v1.ServiceMeshControlPlaneInterface {
	return &FakeServiceMeshControlPlanes{c, namespace}
}

func (c *FakeMaistraV1) ServiceMeshMemberRolls(namespace string) v1.ServiceMeshMemberRollInterface {
	return &FakeServiceMeshMemberRolls{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMaistraV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
