// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	maistrav1 "github.com/maistra/istio-operator/pkg/apis/maistra/v1"
	versioned "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/maistra/clientset/versioned"
	internalinterfaces "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/maistra/informers/externalversions/internalinterfaces"
	v1 "github.com/openshift-knative/knative-serving-networking-openshift/pkg/client/maistra/listers/maistra/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceMeshMemberRollInformer provides access to a shared informer and lister for
// ServiceMeshMemberRolls.
type ServiceMeshMemberRollInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ServiceMeshMemberRollLister
}

type serviceMeshMemberRollInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewServiceMeshMemberRollInformer constructs a new informer for ServiceMeshMemberRoll type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServiceMeshMemberRollInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredServiceMeshMemberRollInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredServiceMeshMemberRollInformer constructs a new informer for ServiceMeshMemberRoll type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredServiceMeshMemberRollInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MaistraV1().ServiceMeshMemberRolls(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MaistraV1().ServiceMeshMemberRolls(namespace).Watch(options)
			},
		},
		&maistrav1.ServiceMeshMemberRoll{},
		resyncPeriod,
		indexers,
	)
}

func (f *serviceMeshMemberRollInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredServiceMeshMemberRollInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *serviceMeshMemberRollInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&maistrav1.ServiceMeshMemberRoll{}, f.defaultInformer)
}

func (f *serviceMeshMemberRollInformer) Lister() v1.ServiceMeshMemberRollLister {
	return v1.NewServiceMeshMemberRollLister(f.Informer().GetIndexer())
}
